### ISSUE TITLE
Retry requests when token expires

### ISSUE THREAD

**Issue by yokomizor** [atados/www#22]
We are rejecting promises when API returns 403:

https://github.com/atados/www/blob/a6e6bf90090affae38856d95eef64496f965cd11/app/scripts/app.js#L151

Some requests are triggered inside resolver functions:

https://github.com/atados/www/blob/a6e6bf90090affae38856d95eef64496f965cd11/app/scripts/app.js#L30

There is no retry or error page when these promises are rejected.

Behavior when token expires:

![unnamed 1](https://cloud.githubusercontent.com/assets/514767/7496095/9192f23a-f3e8-11e4-846b-367f6e7f0b79.png)

I think we should retry these requests a few times and display an error page after that.

**Comment by mpomarole** [comment]
I think it is worth checking the error logs on elastic search on the server as well to see why they are not returning the search results as well do better error handling. I will try to do that this weekend.

**Comment by yokomizor** [comment]
It does not look an elastic search error for me. Note the 403 response status code.

**Comment by mpomarole** [comment]
The problem is in the way the client code is handling access_token authentication. When the token has expired the client is not deleting the old cookie from the browser. The code needs to be updated so the old cookie is deleted and the user is logged out and redirected to the home page to authenticate again.
